PKG_NAME = libzdb
PKG_VERS = 2.10.5
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE =  http://www.tildeslash.com/libzdb/dist
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS = cross/flex

HOMEPAGE = http://www.tildeslash.com
COMMENT  = 
LICENSE  =

GNU_CONFIGURE = 1
CONFIGURE_ARGS = 

include ../../mk/spksrc.cross-cc.mk
